<?php
function landpick_h1_typography_options( $args = array() ){
    $options  = array(
        array(
            'id'       => 'h1-xs',
            'type'     => 'typography',
            'title'    => __( 'H1 extra small', 'landpick' ),
            'subtitle' => __( 'Specify the global h1 font properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h1.h1-xs'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h1-sm',
            'type'     => 'typography',
            'title'    => __( 'H1 small', 'landpick' ),
            'subtitle'    => __( 'h1.h1-sm', 'landpick' ),
            'desc' => __( 'Specify the h1 small properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h1.h1-sm'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h1-md',
            'type'     => 'typography',
            'title'    => __( 'H1 medium', 'landpick' ),
            'subtitle' => __( 'Specify the h1 medium properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h1.h1-md'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h1-lg',
            'type'     => 'typography',
            'title'    => __( 'H1 large', 'landpick' ),
            'subtitle' => __( 'Specify the h1 large properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h1.h1-lg'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h1-xl',
            'type'     => 'typography',
            'title'    => __( 'H1 extra large', 'landpick' ),
            'subtitle' => __( 'Specify the h1 extra large properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h1.h1-xl'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ), 
        array(
            'id'       => 'h1-huge',
            'type'     => 'typography',
            'title'    => __( 'H1 huge', 'landpick' ),
            'subtitle' => __( 'Specify the h1 huge properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h1.h1-huge'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
    );
    return $options;
}