<?php
function landpick_h4_typography_options( $args = array() ){
    $options  = array(
        array(
            'id'       => 'h4-xs',
            'type'     => 'typography',
            'title'    => __( 'H4 extra small', 'landpick' ),
            'subtitle' => __( 'Specify the global h4 font properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h4.h4-xs'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h4-sm',
            'type'     => 'typography',
            'title'    => __( 'H4 small', 'landpick' ),
            'subtitle'    => __( 'h4.h4-sm', 'landpick' ),
            'desc' => __( 'Specify the h4 small properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h4.h4-sm'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h4-md',
            'type'     => 'typography',
            'title'    => __( 'H4 medium', 'landpick' ),
            'subtitle' => __( 'Specify the h4 medium properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h4.h4-md'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h4-lg',
            'type'     => 'typography',
            'title'    => __( 'H4 large', 'landpick' ),
            'subtitle' => __( 'Specify the h4 large properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h4.h4-lg'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h4-xl',
            'type'     => 'typography',
            'title'    => __( 'H4 extra large', 'landpick' ),
            'subtitle' => __( 'Specify the h4 extra large properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h4.h4-xl'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ), 
        array(
            'id'       => 'h4-huge',
            'type'     => 'typography',
            'title'    => __( 'H4 huge', 'landpick' ),
            'subtitle' => __( 'Specify the h4 huge properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h4.h4-huge'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
    );
    return $options;
}