<?php
add_action( 'vc_load_default_templates_action','landpick_hero_sections_for_vc' ); // Hook in
function landpick_hero_sections_for_vc() {
	$templates = array();

	$empty_value = '';

	$templates['Section: Hero 01'] = '[vc_section section_type="hero" hero_type="1" parallax_image_attachment="fixed" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="1/2" column_inner_style="hero-txt" hero_txt_type="1"][perch_hero_text name_font_container="tag:span|text_color:Default|text_underline:none|" title="Organize your business fast & easily with {LandPick}" title_highlight_text_enable="yes" title_highlight_text="text_underline:none|text_color:Default|" title_font_container="tag:h3|size:xl|text_color:Default|text_underline:none|" modal_popup_title_color="0" modal_popup_icon_color="0" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Fjthemes.org%2Fwp%2Flandpick%2Fdemos%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fstore_badges%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Try%2014%20days%20free%20trial%22%2C%22button_url%22%3A%22%23%22%2C%22icon_fontawesome%22%3A%22fa%20fa-angle-double-right%22%2C%22button_target%22%3A%22_self%22%2C%22button_style%22%3A%22btn-blue%22%7D%5D" buttons_desc=""][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="5/12"][perch_image custom_src="'.get_template_directory_uri().'/images/hero-1-img.png" max_width="yes" css_animation="fadeInRight"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 02'] = '[vc_section section_type="hero" hero_type="2" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="5/12"][perch_hero_text title="The best landing page to solve your online business" subtitle="Feugiat primis ligula risus auctor laoreet augue egestas mauris viverra tortor in iaculis pretium magna mauris a rhoncus ipsum feugiat primis in ultrice ligula" modal_popup_title_color="0" modal_popup_icon_color="0" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Flandpick%2Fwp%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Buy%20the%20LandPick%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-rose%22%7D%5D" buttons_desc="" el_class="hero-txt white-color"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="1/2"][perch_hero_image display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-2-img.png"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 03'] = '[vc_section enable_inner="yes" section_type="hero" hero_type="3" bg_class="bg-tra" parallax_image_attachment="scroll" padding_bottom="pb-80" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="5/12"][perch_hero_image display_as="hero-3-img" custom_src="'.get_template_directory_uri().'/images/hero-3-img.png"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="6/12"][perch_hero_text title="Need professional help with your project?" title_font_container="tag:h3|size:lg|text_color:Default|text_underline:none|" subtitle="Semper lacus cursus porta, feugiat primis luctus ultrice tellus potenti neque dolor in magna suscipit magna, mauris rhoncus ipsum" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="hero-txt white-color"][perch_newsletter_form align="text-left" inline_form="yes" button_text="Get Started" button_style="btn-blue" enable_form_requirement="yes" subtitle="'.$empty_value.'" el_class="form-holder hero-newsletter-form white-color"][/vc_column][/vc_row][/vc_section]';	

	$templates['Section: Hero 05'] = '[vc_section section_type="hero" hero_type="5" bg_class="bg-tra" parallax_image_attachment="inherit" padding_class=""][vc_row][vc_column width="2/12"][/vc_column][vc_column width="8/12"][perch_hero_text align="text-center" title="LandPick is the powerful landing page to promote your business" title_font_container="tag:h3|size:md|text_color:Default|text_underline:none|" subtitle="Feugiat primis ligula risus auctor laoreet augue egestas mauris viverra tortor in iaculis pretium magna, mauris rhoncus ipsum" subtitle_font_container="tag:p|size:lg|text_color:Default|text_underline:none|" modal_popup_title_color="0" modal_popup_icon_color="0"][perch_newsletter_form inline_form="yes" subtitle="Try LandPick free for 14 days. No risk, and no credit card required." subtitle_font_container="tag:span|text_color:grey-color|text_underline:none|" el_class="form-holder hero-newsletter-form hero-links"][/vc_column][vc_column width="2/12"][/vc_column][/vc_row][vc_row full_width="stretch_row_content" parallax_image_attachment="inherit" el_class="bg-fixed hero-5-img"][vc_column][/vc_column][/vc_row][/vc_section]';	

	$templates['Section: Hero 06'] = '[vc_section section_type="hero" hero_type="6" parallax_image_attachment="scroll"][vc_row][vc_column width="7/12"][perch_hero_text title="Still looking for the right landing page?" title_font_container="tag:h2|size:lg|text_color:Default|text_underline:none|" subtitle="Feugiat primis ligula risus auctor laoreet augue egestas mauris viverra tortor in iaculis pretium magna, mauris rhoncus ipsum placerat feugiat primis in ultrice ligula tempus auctor" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="hero-txt white-color"][perch_newsletter_form inline_form="yes" enable_form_requirement="yes" subtitle="'.$empty_value.'" el_class="form-holder hero-newsletter-form white-color"][/vc_column][vc_column width="5/12"][perch_hero_image display_as="hero-6-img" custom_src="'.get_template_directory_uri().'/images/hero-6-img.png" max_width="yes"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 07'] = '[vc_section enable_inner="yes" section_type="hero" hero_type="7" bg_class="bg-tra" parallax_image_attachment="inherit" padding_class=""][vc_row][vc_column width="6/12" column_inner_style="hero-txt" hero_txt_type="7"][perch_hero_text name_font_container="tag:h2|size:xl|text_color:Default|text_underline:none|" title="Start your new project with the LandPick" subtitle="Egestas magna egestas magna ipsum vitae purus ipsum primis in cubilia laoreet augue luctus magna dolor luctus magna dolor auctor integer ullam tempor suscipit begestas" subtitle_font_container="tag:p|size:lg|text_color:Default|text_underline:none|" enable_modal_popup="yes" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="hero-txt white-color"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="5/12"][perch_image custom_src="'.get_template_directory_uri().'/images/hero-7-img.png" css_animation="slideInLeft"][/vc_column][/vc_row][vc_row bg_class="bg-white" parallax_image_attachment="inherit" el_class="hero-statistic container"][vc_column][vc_row_inner bg_class="bg-white" parallax_image_attachment="inherit"][vc_column_inner width="1/3"][perch_counter_up align="" icon_flaticon="" prefix="8," title="Downloads"][/vc_column_inner][vc_column_inner width="1/3"][perch_counter_up align="" icon_flaticon="" prefix="5," count="569" title="Tickets Closed"][/vc_column_inner][vc_column_inner width="1/3"][perch_counter_up align="" icon_flaticon="" prefix="14," count="189" title="Followers"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 08'] = '[vc_section section_type="hero" hero_type="8" parallax_image_attachment="fixed" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="1/12"][/vc_column][vc_column width="5/6"][perch_hero_text align="text-center" name_font_container="tag:h2|size:xs|text_color:Default|text_underline:none|" title="Ready for Design Exploration?" subtitle="Feugiat primis ligula risus auctor laoreet augue egestas mauris viverra tortor in iaculis pretium magna, mauris rhoncus ipsum placerat feugiat primis in ultrice ligula tempus auctor" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="hero-txt white-color"][perch_newsletter_form enable_name="yes" name="Your name*" inline_form="yes" button_text="Start Now" button_style="btn-lightgreen" enable_form_requirement="yes" subtitle="'.$empty_value.'" el_class="white-color"][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][/vc_section]';	

	$templates['Section: Hero 09'] = '[vc_section section_type="hero" hero_type="9" parallax_image_attachment="scroll" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="1/12"][/vc_column][vc_column width="5/6"][perch_hero_text align="text-center" title="We create amazing experiences for our clients. Want to try us?" subtitle="Feugiat primis ligula risus auctor laoreet augue egestas mauris viverra tortor in iaculis pretium magna, mauris rhoncus ipsum placerat" subtitle_font_container="tag:p|size:lg|text_color:Default|text_underline:none|" modal_popup_title_color="0" modal_popup_icon_color="0" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Flandpick%2Fwp%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Try%2014%20days%20free%20trial%22%2C%22button_url%22%3A%22%23%22%2C%22icon_fontawesome%22%3A%22fa%20fa-angle-double-right%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-lightblue%22%7D%5D" buttons_desc=""][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][vc_row parallax_image_attachment="inherit"][vc_column][perch_hero_image align="text-center" display_as="hero-9-img" custom_src="'.get_template_directory_uri().'/images/hero-9-img.png"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 10'] = '[vc_section section_type="hero" hero_type="10" bg_class="bg-tra" parallax_image_attachment="fixed" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="5/12"][perch_hero_text title="Manage your workflow with {LandPick}" title_highlight_text_enable="yes" title_highlight_text="text_underline:none|text_color:Default|font_weight:700|" title_font_container="tag:h2|size:lg|text_color:Default|text_underline:none|" subtitle="Semper lacus cursus porta, feugiat primis luctus ultrice tellus potenti neque dolor in magna suscipit begestas magna, mauris rhoncus ipsum" modal_popup_title_color="0" modal_popup_icon_color="0" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Flandpick%2Fwp%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Get%20Started%20Free%22%2C%22button_url%22%3A%22%23%22%2C%22icon_fontawesome%22%3A%22fa%20fa-angle-double-right%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-rose%22%7D%5D" buttons_desc=""][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="1/2"][perch_watch_video2 icon_class="white" title="'.$empty_value.'" subtitle="'.$empty_value.'" el_class="white-color video-block"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 11'] = '[vc_section section_type="hero" hero_type="11" bg_class="bg-dark" parallax_image_attachment="fixed" padding_class="" el_class="hero-11-text" css=".vc_custom_1549803210271{padding-top: 220px !important;background-image: url(http://jthemes.org/wp/landpick/demos/wp-content/uploads/2019/02/hero-11.jpg?id=518) !important;}"][vc_row parallax_image_attachment="inherit"][vc_column width="1/12"][/vc_column][vc_column width="5/6"][perch_hero_text align="text-center" name="Powerful landing page template for business, SaaS and Apps" name_font_container="tag:h2|size:xs|text_color:Default|text_underline:none|" title="Feugiat primis ligula risus auctor laoreet augue egestas mauris viverra tortor in iaculis, mauris rhoncus ipsum placerat luctus magna dolor luctus" title_font_container="tag:p|size:lg|text_color:Default|text_underline:none|" subtitle="'.$empty_value.'" modal_popup_title_color="0" modal_popup_icon_color="0" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Fjthemes.org%2Fwp%2Flandpick%2Fdemos%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Try%2014%20days%20free%20trial%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-lightblue%22%2C%22button_size%22%3A%22btn-md%22%7D%5D" buttons_desc="" mbottom="mb-40"][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][vc_row][vc_column column_inner_style="hero-img" hero_type="11"][perch_image align="text-center" custom_src="http://jthemes.org/wp/landpick/demos/wp-content/themes/landpick/images/hero-11-img.png"][/vc_column][/vc_row][/vc_section]
';

	$templates['Section: Hero 12'] = '[vc_section section_type="hero" hero_type="12" bg_class="bg-tra" parallax_image_attachment="fixed"][vc_row parallax_image_attachment="inherit"][vc_column width="1/12"][/vc_column][vc_column width="5/6"][perch_hero_text align="text-center" title="Over 2000+ companies are already using LandPick every day" subtitle="Egestas magna egestas magna ipsum vitae purus ipsum primis in cubilia laoreet augue luctus magna dolor luctus undo magna an dolor vitae integer odio" subtitle_font_container="tag:p|size:lg|text_color:Default|text_underline:none|" modal_popup_title_color="0" modal_popup_icon_color="0" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Flandpick%2Fwp%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Get%20Started%20Now%22%2C%22button_url%22%3A%22%23%22%2C%22icon_fontawesome%22%3A%22fa%20fa-angle-double-right%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-rose%22%7D%5D" buttons_desc="" el_class="hero-txt white-color"][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 13'] = '[vc_section bg_class="bg-tra" parallax_image_attachment="fixed" padding_top="pt-120" padding_bottom="pb-100" padding_class="" margin_top="mt-40" el_id="hero-13"][vc_row parallax_image_attachment="inherit"][vc_column width="1/2"][perch_hero_text title="How we created our amazing website with LandPick template" subtitle="Egestas magna egestas magna ipsum vitae purus ipsum primis cubilia laoreet augue luctus magna dolor luctus undo magna an dolor vitae vitae auctor integer primis laoreet" modal_popup_title_color="0" modal_popup_icon_color="0" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Flandpick%2Fwp%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Buy%20Now%20(%2429.99)%22%2C%22button_url%22%3A%22%23%22%2C%22icon_fontawesome%22%3A%22fa%20fa-angle-double-right%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-blue%22%7D%5D" buttons_desc="*Avaliable in PDF, ePUB, Mobi & Kindle." el_class="hero-txt white-color"][/vc_column][vc_column width="1/2"][perch_hero_image display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-13-img.png" el_class="hero-13-img"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 14'] = '[vc_section enable_inner="yes" section_type="hero" hero_type="14" bg_class="bg-grey" parallax_image_attachment="inherit" padding_class=""][vc_row][vc_column width="7/12"][perch_hero_text name_font_container="tag:h2|size:sm|text_color:Default|text_underline:none|" title="We\'re ready to give you {the Best Business Consultations}" title_highlight_text_enable="yes" title_highlight_text="text_underline:none|text_color:blue-color|" title_font_container="tag:h2|size:sm|text_color:black-color|text_underline:none|letter_spacing:0em|" subtitle="Egestas magna egestas magna ipsum vitae purus ipsum primis in cubilia laoreet augue luctus magna dolor luctus magna" subtitle_font_container="tag:p|size:md|text_color:black-color|text_underline:none|" enable_modal_popup="yes" modal_popup_title_color="0" modal_popup_icon_color="bluebayoux-color"][/vc_column][vc_column width="5/12"][perch_hero_image display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-14-img.png"][/vc_column][/vc_row][/vc_section][vc_row bg_class="bg-bluebayoux" parallax_image_attachment="inherit" css=".vc_custom_1549898807495{margin-right: 55px !important;margin-left: 60px !important;}" el_class="hero-boxes white-color"][vc_column width="1/3"][perch_vc_title title="1. Business Planning" title_font_container="tag:h5|size:sm|text_color:Default|text_underline:none|extra_class:os-version|" subtitle="Egestas magna ipsum vitae purus ipsum primis in cubilia laoreet augue luctus magna dolor luctus undo magna an dolor vitae" subtitle_font_container="tag:p|text_color:Default|text_underline:none|extra_class:os-version|" el_class="hbox-1"][/vc_column][vc_column width="1/3"][perch_vc_title title="2. Business Investment" title_font_container="tag:h5|size:sm|text_color:Default|text_underline:none|extra_class:os-version|" subtitle="Egestas magna ipsum vitae purus ipsum primis in cubilia laoreet augue luctus magna dolor luctus undo magna an dolor vitae" subtitle_font_container="tag:p|text_color:Default|text_underline:none|extra_class:os-version|" el_class="hbox-1"][/vc_column][vc_column width="1/3"][perch_vc_title title="3. Business Sustainability" title_font_container="tag:h5|size:sm|text_color:Default|text_underline:none|extra_class:os-version|" subtitle="Egestas magna ipsum vitae purus ipsum primis in cubilia laoreet augue luctus magna dolor luctus undo magna an dolor vitae" subtitle_font_container="tag:p|text_color:Default|text_underline:none|extra_class:os-version|" el_class="hbox-1"][/vc_column][/vc_row]';

	$templates['Section: Hero 16'] = '[vc_section section_type="hero" hero_type="16" parallax_image_attachment="scroll" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="1/12"][/vc_column][vc_column width="5/6"][perch_hero_text align="text-center" title="High Converting Landing Page" title_font_container="tag:h2|text_color:Default|text_underline:none|" subtitle="'.$empty_value.'" modal_popup_title_color="0" modal_popup_icon_color="0" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Flandpick%2Fwp%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22%20Join%20with%20Facebook%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-tra-white%20tra-hover%22%7D%2C%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Flocalhost%2Flandpick%2Fwp%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fgoogleplay.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22%20Use%20email%20instead%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-lightblue%22%7D%5D" buttons_desc="" el_class="hero-txt white-color"][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][vc_row parallax_image_attachment="inherit"][vc_column width="1/12"][/vc_column][vc_column width="10/12"][vc_row_inner parallax_image_attachment="inherit"][vc_column_inner el_class="b-right" width="1/3"][perch_feature_box display_as="" icon_flaticon="flaticon-040-settings" icon_color="white-color" title="'.$empty_value.'" title_font_container="tag:h5|size:sm|text_color:white-color|text_underline:none|" subtitle="Auctor velna congue undo impedit magna" subtitle_font_container="tag:p|text_color:white-color|text_underline:none|extra_class:hbox-2-txt|" el_class="hbox-2"][/vc_column_inner][vc_column_inner el_class="b-right" width="1/3"][perch_feature_box display_as="" icon_color="white-color" title="'.$empty_value.'" subtitle="Vitae donec mauris lectus laoreet gestas" subtitle_font_container="tag:p|text_color:white-color|text_underline:none|extra_class:hbox-2-txt|" el_class="hbox-2"][/vc_column_inner][vc_column_inner el_class="b-right" width="1/3"][perch_feature_box display_as="" icon_flaticon="flaticon-007-map" icon_color="white-color" title="'.$empty_value.'" subtitle="Gravida magna is congue viverra luctus dolor" subtitle_font_container="tag:p|text_color:white-color|text_underline:none|extra_class:hbox-2-txt|" el_class="hbox-2"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 17'] = '[vc_section section_type="hero" hero_type="17" bg_class="bg-lightgrey" parallax_image_attachment="fixed" padding_class="" css=".vc_custom_1549900762704{padding-top: 220px !important;padding-bottom: 100px !important;background-image: url(http://jthemes.org/wp/landpick/demos/wp-content/uploads/2019/02/hero-17.jpg?id=573) !important;}"][vc_row][vc_column width="7/12"][perch_hero_text title="We Bring Emotion To Your Projects" title_font_container="tag:h2|size:xl|text_color:Default|text_underline:none|" subtitle="Feugiat primis ligula risus auctor and laoreet augue egestas mauris viverra tortor in iaculis, mauris rhoncus ipsum placerat luctus magna dolor luctus ligula risus auctor laoreet" subtitle_font_container="tag:p|size:lg|text_color:Default|text_underline:none|" modal_popup_title_color="0" modal_popup_icon_color="0" enable_buttons="yes" params="%5B%7B%22button_type%22%3A%22text_btn%22%2C%22img_btn%22%3A%22http%3A%2F%2Fjthemes.org%2Fwp%2Flandpick%2Fdemos%2Fwp-content%2Fthemes%2Flandpick%2Fimages%2Fappstore.png%22%2C%22img_btn_size%22%3A%22160%22%2C%22button_text%22%3A%22Try%2014%20days%20free%20trial%22%2C%22button_url%22%3A%22%23%22%2C%22button_target%22%3A%22_blank%22%2C%22button_style%22%3A%22btn-blue%22%2C%22button_size%22%3A%22btn-md%22%7D%5D" buttons_desc="No credit card required! Cancel anytime"][/vc_column][vc_column width="5/12"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Hero 18'] = '[vc_section bg_class="bg-lightgrey" parallax_image_attachment="inherit" padding_top="pt-120" padding_class="" el_id="hero-18"][vc_row parallax_image_attachment="inherit"][vc_column width="7/12"][perch_hero_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/hero-18-img.png" el_class="hero-img hero-18-img"][/vc_column][vc_column width="5/12" el_id="hero-form"][perch_hero_text title="Every great business starts with an idea" title_font_container="tag:h3|size:xs|text_color:Default|text_underline:none|" subtitle="Feugiat primis ligula risus auctor and laoreet augue mauris viverra tortor in iaculis, mauris vitae" modal_popup_title_color="0" modal_popup_icon_color="0"][vc_row_inner parallax_image_attachment="inherit" el_class="hero-form"][vc_column_inner el_class="quick-form "][perch_newsletter_form enable_name="yes" name="Enter your name" email="Enter your email" button_text="Get Started Now" button_style="btn-blue" enable_form_requirement="yes" subtitle="'.$empty_value.'"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][/vc_section]';








	
	foreach ($templates as $key => $template) {
		$data               = array(); 
	    $data['name']       = esc_attr($key); // Assign name for your custom template
	    $data['weight']     = 0; 
	    $data['image_path'] = '';
	    $data['custom_class'] = ''; // CSS class name
	    $data['content']    = $template;

	    vc_add_default_templates( $data );
	}
      

}



