<?php
add_action( 'vc_load_default_templates_action','landpick_content_sections_for_vc' ); // Hook in
function landpick_content_sections_for_vc() {
	$templates = array();

	$templates['Section: Content 01'] = '[vc_section section_type="content" content_type="1" parallax_image_attachment="inherit"][vc_row parallax_image_attachment="inherit"][vc_column width="1/2"][perch_content_text name="" title="Bring your ideas to life with LandPick" title_font_container="tag:h3|size:xs|text_color:Default|text_underline:none|" subtitle="An enim nullam tempor sapien gravida donec enim ipsum pretium porta justo integer at odio velna vitae auctor integer congue magna at purus pretium ligula rutrum luctus risus ultrice congue gravida." subtitle_font_container="tag:p|text_color:Default|text_underline:none|" enable_content_list="yes" content_list="Vitae auctor integer congue magna at pretium purus pretium ligula rutrumluctus risus ac risus auctor ,Tempor sapien gravida donec enim ipsum blandit magna at purus pretium ligula rutrum luctus gravida donec porta justo integer,Integer congue magna at pretium purus pretium ligula rutrumluctus risus ac pretium ligula rutrum luctus ultrice gravida" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="content-txt content-left"]
		<h5 class="h5-sm wow fadeInUp" style="visibility: visible; animation-delay: 0.7s; animation-name: fadeInUp;" data-wow-delay="0.7s">Feature Integration</h5>
		[/perch_content_text][/vc_column][vc_column width="1/2"][perch_content_image display_as="0" custom_src="'.get_template_directory_uri().'/images/image-01.png"][/vc_column][/vc_row][/vc_section]';	

	$templates['Section: Content 02'] = '[vc_section section_type="content" content_type="2" bg_class="bg-lightgrey" parallax_image_attachment="inherit"][vc_row parallax_image_attachment="inherit"][vc_column width="1/2"][perch_content_image display_as="0" custom_src="'.get_template_directory_uri().'/images/image-02.png" css_animation="fadeInLeft"][/vc_column][vc_column width="1/2"][perch_content_text name="" title="We are making design better for everyone" title_font_container="tag:h3|size:xs|text_color:Default|text_underline:none|" subtitle="Semper lacus cursus porta, feugiat primis in ultrice ligula tempus auctor ipsum and mauris lectus enim ipsum" subtitle_font_container="tag:p|size:md|text_color:grey-color|text_underline:none|" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="content-txt content-right"]
		<h5 class="h5-sm wow fadeInUp" data-wow-delay="0.7s">Feature Integration</h5>
		<p class="wow fadeInUp" data-wow-delay="0.9s">An nullam tempor sapien, eget gravida donec enim ipsum porta justo integer at odio velna auctor integer congue. Justo odio integer a velna lectus aenean magna and mauris lectus laoreet tempor</p>
		<p class="wow fadeInUp" data-wow-delay="1.1s">Semper lacus cursus porta primis ligula risus tempus sagittis ipsum and mauris lectus laoreet purus tempor ipsum at enim ipsum porta justo integer ultrice ligula lectus aenean magna and mauris</p>
		[/perch_content_text][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 03'] = '[vc_section section_type="content" content_type="3" parallax_image_attachment="inherit"][vc_row parallax_image_attachment="inherit" el_id="c3-top" el_class="pb-50"][vc_column width="1/2"][perch_content_image display_as="0" custom_src="'.get_template_directory_uri().'/images/image-11.jpg"][/vc_column][vc_column width="1/2"][perch_content_text name="" title="With knowledge, skills and hard work" title_font_container="tag:h3|size:xs|text_color:Default|text_underline:none|" subtitle="An enim nullam tempor sapien gravida donec enim ipsum pretium porta justo integer at odio velna vitae auctor integer congue magna at purus pretium ligula rutrum luctus risus ultrice enim gravida" subtitle_font_container="tag:p|text_color:Default|text_underline:none|" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="content-txt content-right"]

		Aliquam a augue suscipit, luctus neque purus ipsum neque dolor primis libero tempus, tempor posuere ligula varius augue luctus donec sapien posuere ligula varius impedit enim tempor sapien

		[/perch_content_text][/vc_column][/vc_row][vc_row parallax_image_attachment="inherit" el_id="c3-bottom"][vc_column width="2/12"][/vc_column][vc_column width="8/12"][perch_content_image align="text-center" display_as="0" custom_src="'.get_template_directory_uri().'/images/image-13.jpg"][perch_content_text name="" title="Start your project with LandPick" title_font_container="tag:h3|size:xs|text_color:Default|text_underline:none|" subtitle_font_container="tag:p|text_color:Default|text_underline:none|" modal_popup_title_color="0" modal_popup_icon_color="0"]

		An enim nullam tempor sapien gravida donec enim ipsum pretium porta justo integer at odio velna vitae auctor integer congue magna at purus pretium ligula rutrum luctus risus ultrice enim gravida. Maecenas laoreet augue egestas laoreet augue egestas, congue gestas volutpat posuere cubilia congue ipsum mauris lectus laoreet gestas neque volutpat and gestas posuere

		[/perch_content_text][/vc_column][vc_column width="2/12"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 04'] = '[vc_section section_type="content" content_type="4" parallax_image_attachment="inherit" padding_class="wide-50"][vc_row parallax_image_attachment="inherit"][vc_column width="2/12"][/vc_column][vc_column width="8/12" el_class="cbox-1"][perch_vc_title title="1. Extended Features" title_font_container="tag:h4|size:xs|text_color:Default|text_underline:none|extra_class:os-version|" subtitle="Semper lacus cursus porta, feugiat primis in ultrice ligula tempus auctor ipsum and mauris lectus enim ipsum enim gravida purus pretium ligula. emper lacus cursus porta, feugiat primis in ultrice ligula auctor ipsum and mauris lectus enim ipsum enim gravida purus pretium tempus" subtitle_font_container="tag:p|text_color:Default|text_underline:none|extra_class:os-version|" el_class="content-txt"][perch_content_image display_as="0" custom_src="'.get_template_directory_uri().'/images/image-06.png"][/vc_column][vc_column width="2/12"][/vc_column][/vc_row][vc_row parallax_image_attachment="inherit"][vc_column width="2/12"][/vc_column][vc_column width="8/12" el_class="cbox-1"][perch_vc_title title="2. Clean &amp; Beautiful Docs" title_font_container="tag:h4|size:xs|text_color:Default|text_underline:none|extra_class:os-version|" subtitle="Semper lacus cursus porta, feugiat primis in ultrice ligula tempus auctor ipsum and mauris lectus enim ipsum enim gravida purus pretium ligula. emper lacus cursus porta, feugiat primis in ultrice ligula auctor ipsum and mauris lectus enim ipsum enim gravida purus pretium tempus" subtitle_font_container="tag:p|text_color:Default|text_underline:none|extra_class:os-version|" el_class="content-txt"][perch_content_image display_as="0" custom_src="'.get_template_directory_uri().'/images/image-05.png"][/vc_column][vc_column width="2/12"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 05'] = '[vc_section section_type="content" content_type="5" parallax_image_attachment="inherit" padding_top="pt-100" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="1/2"][perch_content_text name="" title="Choose a powerful design for your website" title_font_container="tag:h3|size:xs|text_color:Default|text_underline:none|" subtitle="An nullam tempor sapien, eget gravida donec enim ipsum porta justo integer at odio velna auctor integer congue. Justo odio integer a velna lectus aenean magna and mauris lectus laoreet tempor" subtitle_font_container="tag:p|text_color:Default|text_underline:none|" enable_content_list="yes" content_list="Vitae auctor integer congue magna at pretium purus pretium ligula rutrumluctus risus ac risus auctor,Tempor sapien gravida donec enim ipsum blandit magna at purus pretium ligula rutrum luctus gravida donec porta justo integer,Justo odio integer a velna lectus aenean magna and mauris lectus pretium ligula rutrum luctus risus ac risus auctor gravida donec" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="content-txt content-left"]
		<h5 class="h5-sm wow fadeInUp" data-wow-delay="0.7s">DataBase Backup</h5>
		[/perch_content_text][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="5/12"][perch_content_image display_as="content-5-img" custom_src="'.get_template_directory_uri().'/images/image-10.png" max_width="yes"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 06'] = '[vc_section section_type="content" content_type="6" parallax_image_attachment="inherit"][vc_row parallax_image_attachment="inherit"][vc_column width="5/12"][perch_content_image display_as="content-6-img" custom_src="'.get_template_directory_uri().'/images/image-08.png" max_width="yes" css_animation="fadeInLeft"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="1/2"][perch_content_text name="" title="Solve your online business with LandPick" title_font_container="tag:h3|size:xs|text_color:Default|text_underline:none|" subtitle="An nullam tempor sapien, eget gravida donec enim ipsum porta justo integer at odio velna auctor integer congue. Justo odio integer a velna lectus aenean magna and mauris lectus laoreet tempor" subtitle_font_container="tag:p|text_color:Default|text_underline:none|" enable_content_list="yes" content_list="Vitae auctor integer congue magna at pretium purus pretium ligula rutrumluctus risus ac risus auctor,Tempor sapien gravida donec enim ipsum blandit magna at purus pretium ligula rutrum luctus gravida donec porta justo integer,Justo odio integer a velna lectus aenean magna and mauris lectus pretium ligula rutrum luctus risus ac risus auctor gravida donec" modal_popup_title_color="0" modal_popup_icon_color="0" el_class="content-txt content-right"]
		<h5 class="h5-sm wow fadeInUp" data-wow-delay="0.7s">Real Time Customization</h5>
		[/perch_content_text][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 07'] = '[vc_section section_type="content" content_type="7" parallax_image_attachment="inherit"][vc_row parallax_image_attachment="inherit"][vc_column width="6/12"][perch_content_text name="" title="Plan and manage your projects with LandPick" subtitle="Semper lacus cursus porta, feugiat primis in ultrice ligula tempus auctor ipsum and mauris lectus enim ipsum" modal_popup_title_color="0" modal_popup_icon_color="0"][/perch_content_text][perch_list list_title="" list_group="%5B%7B%22title%22%3A%22Create%20your%20account%22%2C%22subtitle%22%3A%22Aliquam%20a%20augue%20suscipit%2C%20luctus%20neque%20purus%20ipsum%20neque%20dolor%20primis%20libero%20tempus%2C%20tempor%20posuere%20ligula%20varius%20%22%7D%2C%7B%22title%22%3A%22Customize%20your%20profile%22%2C%22subtitle%22%3A%22At%20sagittis%20congue%20augue%20egestas%20egestas%20magna%20ipsum%20vitae%20purus%20ipsum%20primis%20in%20cubilia%20laoreet%20augue%20diam%20ociis%20nullam%20%22%7D%2C%7B%22title%22%3A%22Sync%20your%20data%22%2C%22subtitle%22%3A%22Semper%20lacus%20cursus%20porta%2C%20feugiat%20primis%20in%20ultrice%20ligula%20tempus%20auctor%20ipsum%20and%20mauris%20lectus%20enim%20ipsum%20%22%7D%5D" title_font_container="tag:h5|size:xs|text_color:Default|text_underline:none|"][/vc_column][vc_column width="1/12"][/vc_column][vc_column width="5/12"][perch_content_image display_as="content-7-img" custom_src="http://jthemes.org/wp/landpick/demos/wp-content/themes/landpick/images/image-07.png"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 08'] = '[vc_section section_type="content" content_type="8" bg_class="bg-lightgrey" parallax_image_attachment="inherit"][vc_row parallax_image_attachment="inherit"][vc_column][perch_section_title title="Optimized Business Platform" title_font_container="tag:h3|size:md|text_color:Default|text_underline:none|" subtitle="Aliquam a augue suscipit, luctus neque purus ipsum neque dolor primis libero tempus, tempor posuere ligula varius ullam libero" subtitle_font_container="tag:p|size:md|text_color:Default|text_underline:none|"][/vc_column][/vc_row][vc_row parallax_image_attachment="inherit"][vc_column width="1/2"][perch_content_image display_as="0" custom_src="http://jthemes.org/wp/landpick/demos/wp-content/themes/landpick/images/image-04.png"][/vc_column][vc_column width="1/2"][vc_row_inner parallax_image_attachment="inherit" el_class="c8-boxes content-right"][vc_column_inner][perch_feature_box display_as="" icon_color="blueyonder-color" title="User Data Protection" title_font_container="tag:h5|size:sm|text_color:Default|text_underline:none|extra_class:cbox-2-txt|" subtitle="Velna iaculis odio auctor integer congue impedit magna viverra at dolor vitae donec mauris lectus laoreet gestas neque feugiat luctus" subtitle_font_container="tag:p|text_color:grey-color|text_underline:none|extra_class:cbox-2-txt|" el_class="cbox-2"][perch_feature_box display_as="" icon_flaticon="flaticon-079-layer" icon_color="blueyonder-color" title="DataBase Backup" title_font_container="tag:h5|size:sm|text_color:Default|text_underline:none|extra_class:cbox-2-txt|" subtitle="Velna iaculis odio auctor integer congue impedit magna viverra at dolor vitae donec mauris lectus laoreet gestas neque feugiat luctus" subtitle_font_container="tag:p|text_color:grey-color|text_underline:none|extra_class:cbox-2-txt|" el_class="cbox-2"][perch_feature_box display_as="" icon_flaticon="flaticon-040-settings" icon_color="blueyonder-color" title="Real Time Customization" title_font_container="tag:h5|size:sm|text_color:Default|text_underline:none|extra_class:cbox-2-txt|" subtitle="Velna iaculis odio auctor integer congue impedit magna viverra at dolor vitae donec mauris lectus laoreet gestas neque feugiat luctus" subtitle_font_container="tag:p|text_color:grey-color|text_underline:none|extra_class:cbox-2-txt|" el_class="cbox-2"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][/vc_section]';


	$templates['Section: Content 09'] = '[vc_section section_type="content" content_type="9" bg_class="bg-lightgrey" parallax_image_attachment="inherit" padding_top="pt-100" padding_class=""][vc_row parallax_image_attachment="inherit"][vc_column width="1/12"][/vc_column][vc_column width="5/6"][perch_section_title title="We\'re LandPick Simple & Elegant" title_font_container="tag:h3|size:md|text_color:Default|text_underline:none|" subtitle="Gravida donec integer ipsum porta justo at odio velna vitae auctor integer magna at risus auctor purus rutrum primis ultrice ligula luctus impedit magna dolor vitae risuss. An enim nullam tempor sapien gravida donec enim ipsum porta pretium justo integer at odio velna vitae auctor" subtitle_font_container="tag:p|size:md|text_color:Default|text_underline:none|"][/vc_column][vc_column width="1/12"][/vc_column][/vc_row][vc_row parallax_image_attachment="inherit"][vc_column][perch_image align="text-center" custom_src="'.get_template_directory_uri().'/images/image-09.png"][/vc_column][/vc_row][/vc_section]';

	$templates['Section: Content 10'] = '[vc_section enable_inner="yes" section_type="content" content_type="10" inner_padding_top="pt-100" bg_class="bg-tra" parallax_image_attachment="scroll" padding_bottom="pb-100" padding_class="" css=".vc_custom_1549801508960{background-image: url(http://jthemes.org/wp/landpick/demos/wp-content/uploads/2019/02/blue-abstract.jpg?id=411) !important;}"][vc_row parallax_image_attachment="inherit"][vc_column][perch_section_title title="Manage Your Workflow with LandPick" title_font_container="tag:h3|size:md|text_color:Default|text_underline:none|" subtitle="Gravida donec integer ipsum porta justo at odio velna vitae auctor integer magna at risus auctor purus rutrum primis ultrice ligula luctus impedit magna dolor vitae risus" subtitle_font_container="tag:p|size:md|text_color:Default|text_underline:none|" el_class="section-title white-color"][/vc_column][/vc_row][vc_row row_class="content-boxes" bg_class="bg-white" parallax_image_attachment="inherit" css=".vc_custom_1549790461917{margin-right: 55px !important;margin-left: 60px !important;}"][vc_column width="1/2"][perch_feature_box display_as="" icon_type="image" icon_image="http://jthemes.org/wp/landpick/demos/wp-content/themes/landpick/images/icons/design.png" img_icon_size="70" title="Create Your Account" title_font_container="tag:h5|size:sm|text_color:dark-color|text_underline:none|extra_class:cbox-3-txt|" subtitle="Gravida donec integer ipsum porta justo at odio velna vitae auctor integer magna at risus auctor purus rutrum primis ultrice ligula luctus" subtitle_font_container="tag:p|text_color:dark-color|text_underline:none|extra_class:cbox-3-txt|" el_class="cbox-3"][/vc_column][vc_column width="1/2"][perch_feature_box display_as="" icon_type="image" icon_image="http://jthemes.org/wp/landpick/demos/wp-content/themes/landpick/images/icons/analytics-2.png" img_icon_size="70" title="Real Time Customization" title_font_container="tag:h5|size:sm|text_color:dark-color|text_underline:none|extra_class:cbox-3-txt|" subtitle="Gravida donec integer ipsum porta justo at odio velna vitae auctor integer magna at risus auctor purus rutrum primis ultrice ligula luctus" subtitle_font_container="tag:p|text_color:dark-color|text_underline:none|extra_class:cbox-3-txt|" el_class="cbox-3"][/vc_column][/vc_row][/vc_section]';


	
	foreach ($templates as $key => $template) {
		$data               = array(); 
	    $data['name']       = esc_attr($key); // Assign name for your custom template
	    $data['weight']     = 0; 
	    $data['image_path'] = '';
	    $data['custom_class'] = ''; // CSS class name
	    $data['content']    = $template;

	    vc_add_default_templates( $data );
	}
      

}



