<?php
function landpick_h3_typography_options( $args = array() ){
    $options  = array(
        array(
            'id'       => 'h3-xs',
            'type'     => 'typography',
            'title'    => __( 'H3 extra small', 'landpick' ),
            'subtitle' => __( 'Specify the global h3 font properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h3.h3-xs'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h3-sm',
            'type'     => 'typography',
            'title'    => __( 'H3 small', 'landpick' ),
            'subtitle'    => __( 'h3.h3-sm', 'landpick' ),
            'desc' => __( 'Specify the h3 small properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h3.h3-sm'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h3-md',
            'type'     => 'typography',
            'title'    => __( 'H3 medium', 'landpick' ),
            'subtitle' => __( 'Specify the h3 medium properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h3.h3-md'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h3-lg',
            'type'     => 'typography',
            'title'    => __( 'H3 large', 'landpick' ),
            'subtitle' => __( 'Specify the h3 large properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h3.h3-lg'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
        array(
            'id'       => 'h3-xl',
            'type'     => 'typography',
            'title'    => __( 'H3 extra large', 'landpick' ),
            'subtitle' => __( 'Specify the h3 extra large properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h3.h3-xl'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ), 
        array(
            'id'       => 'h3-huge',
            'type'     => 'typography',
            'title'    => __( 'H3 huge', 'landpick' ),
            'subtitle' => __( 'Specify the h3 huge properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('h3.h3-huge'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                 
                'font-size'     => '',               
            ),
        ),
    );
    return $options;
}