<?php
function landpick_paragraph_typography_options( $args = array() ){
    $options  = array(
        array(
            'id'       => 'p',
            'type'     => 'typography',
            'title'    => __( 'Paragraph Font', 'landpick' ),
            'subtitle' => __( 'Specify the global Paragraph font properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'font-backup' => false,
            'non-google' => 'Arial',
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('p'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                
                'font-size'     => '1rem',               
            ),
        ),
        array(
            'id'       => 'p-sm',
            'type'     => 'typography',
            'title'    => __( 'Paragraph small', 'landpick' ),
            'subtitle' => __( 'Specify the paragraph small properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('p.p-sm'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                  
                'font-size'     => '0.95rem',               
            ),
        ),
        array(
            'id'       => 'p-md',
            'type'     => 'typography',
            'title'    => __( 'Paragraph medium', 'landpick' ),
            'subtitle' => __( 'Specify the paragraph medium properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('p.p-md'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                
                'font-size'     => '1.125rem',               
            ),
        ),
        array(
            'id'       => 'p-lg',
            'type'     => 'typography',
            'title'    => __( 'Paragraph large', 'landpick' ),
            'subtitle' => __( 'Specify the paragraph large properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('p.p-lg'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',               
                'font-size'     => '1.25rem',               
            ),
        ),
        array(
            'id'       => 'p-xl',
            'type'     => 'typography',
            'title'    => __( 'Paragraph extra large', 'landpick' ),
            'subtitle' => __( 'Specify the paragraph extra large properties.', 'landpick' ),
            'font_family_clear' => true,
            'google'   => true,
            'letter-spacing'=> true,
            'font-size'     => true,
            'line-height'   => true,
            'text-align'   => false,
            'units'       => 'rem',
            'output' => array('p.p-xl'),
            'default'  => array(
                'color'       => '',
                'font-style'  => '',
                'font-family' => '',                
                'font-size'     => '1.3175rem',               
            ),
        ), 
    );

    return apply_filters( 'landpick/paragraph_typography_options', $options, $args );
}